sudo: false
language: generic

cache:
  apt: true
  directories:
    - /tmp/tools

matrix:
  include:
    - env: CXX=g++-8
      addons:
        apt:
          packages:
            - g++-8
            - libjpeg8-dev
            - libpng-dev
            - libasound2-dev
            - alsa-utils
            - alsa-oss
            - libx11-dev
            - libxft-dev
            - libxcursor-dev
          sources:
            - ubuntu-toolchain-r-test
            
  allow_failures:		
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libjpeg8-dev
            - libpng-dev
            - libasound2-dev
            - alsa-utils
            - alsa-oss
            - libx11-dev
            - libxft-dev
            - libxcursor-dev
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise 

before_install:
  # donwload nana-demo first
  # we are in:  'user'/nana/
  - cd ..
  # we are in:   'user'/
  - git clone --depth=1 --branch=master https://github.com/qPCR4vir/nana-demo.git nana-demo
  # now we have 'user'/nana-demo, 'user'/nana/  and we are in: 'user'/
  - export PATH="$HOME/bin:$PATH"
  - wget --no-check-certificate --no-clobber -O /tmp/tools/cmake https://cmake.org/files/v3.12/cmake-3.12.0-rc3-Linux-x86_64.sh || true
  - chmod -R +x /tmp/tools

install:
  - /tmp/tools/cmake --prefix="$HOME" --exclude-subdir

before_script :
  - mkdir demo-build
  - cd demo-build
  # now we have 'user'/nana-demo, 'user'/nana/ , 'user'/demo-build/ and we are in: 'user'/demo-build/

services:
  # travis don't have a physical monitor. We need to install an emulator:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - xvfb

script:
  - cmake -G"Unix Makefiles" ../nana-demo -DCMAKE_INSTALL_PREFIX=.. -DNANA_CMAKE_ENABLE_JPEG=ON -DNANA_CMAKE_FIND_BOOST_FILESYSTEM=OFF -DNANA_CMAKE_AUTOMATIC_GUI_TESTING=ON -DNANA_CMAKE_INSTALL=OFF
  - make install
  - ctest --verbose  # todo set correct working directory, and show output
  # we have installed in 'user'/ ('user'/demo-build/..), and cmake created 'user'/nana-test/
  # todo: separate resources from sources (a directory for images)
  - ls
  # we were still in: 'user'/demo-build/
  - cd ../nana-test/bin
  - ls -lh


