sudo: false
language: generic

cache:
  apt: true
  directories:
    - /tmp/tools

matrix:
  include:
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libjpeg8-dev
            - libpng-dev
            - libasound2-dev
            - alsa-utils
            - alsa-oss
            - libx11-dev
            - libxft-dev
            - libboost-filesystem-dev
          sources: 
            - ubuntu-toolchain-r-test
    - env: CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          packages:
            - g++-4.9
            - libjpeg8-dev
            - libpng-dev
            - libasound2-dev
            - alsa-utils
            - alsa-oss
            - libx11-dev
            - libxft-dev
          sources: 
            - ubuntu-toolchain-r-test
            
  allow_failures:		
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libjpeg8-dev
            - libpng-dev
            - libasound2-dev
            - alsa-utils
            - alsa-oss
            - libx11-dev
            - libxft-dev
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise 

before_install:
  - git clone --depth=1 --branch=dev_nana_in_examples https://github.com/qPCR4vir/nana-demo.git nana-demo
  - export PATH="$HOME/bin:$PATH"
  - mkdir ~/bin
  - wget --no-check-certificate --no-clobber -O /tmp/tools/cmake https://cmake.org/files/v3.4/cmake-3.4.0-rc3-Linux-x86_64.sh || true
  - chmod -R +x /tmp/tools

install:
  - /tmp/tools/cmake --prefix="$HOME" --exclude-subdir

before_script :
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - mkdir bld
  - cd bld

script:
  - cmake -G"Unix Makefiles" .. -DNANA_CMAKE_ENABLE_JPEG=ON -DNANA_CMAKE_ENABLE_PNG=OFF -DNANA_CMAKE_BUILD_DEMOS=ON -DNANA_CMAKE_ENABLE_AUDIO=OFF -DNANA_CMAKE_FIND_BOOST_FILESYSTEM=ON -DNANA_CMAKE_INCLUDE_EXPERIMENTAL_DEMOS=OFF -DNANA_CMAKE_AUTOMATIC_GUI_TESTING=ON -DNANA_CMAKE_ADD_DEF_AUTOMATIC_GUI_TESTING=ON
  - make
  - ls
  - ./clicked
  - ./HelloWord
  - ./background-effects
  - ./categ
  - ./decore
  - ./dock
  - ./drag-button
  - ./draw
  - ./file_explorer
  #- ./example_menu
  - ./example_listbox
  #- ./example_combox
  #- ./example.button
  #- ./MontiHall
  - ./a_group_impl
  #- ./animate-bmp
  #- ./calculator  
  #- ./helloworld_demo 
  #- ./notepad 
  


